---
# docker-compose -f docker-compose.yaml up -d
version: '3.8'
services:
  database:
    image: mongo:7.0.9
    container_name: 'mongodb-7.0.9'
    ports:
      - '27017-27019:27017-27019'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adminuser
      - MONGO_INITDB_ROOT_PASSWORD=980c2a3a1c3546549fe4210124437068
    networks:
      - local_net_1
networks:
  local_net_1:
    driver: bridge
    external: true