quarkus:
  arc:
    remove-unused-beans: none
  package:
    type: jar
  application:
    name: "backend-dummy-project"
  http:
    root-path: /backend-dummy-project
    so-reuse-port: true
    tcp-quick-ack: true
    tcp-cork: true
    tcp-fast-open: true
    port: 8084
    cors:
      methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      access-control-max-age: PT3M
  vertx:
    max-event-loop-execute-time: 25M
    prefer-native-transport: true
  mongodb:
    connection-string: mongodb://LocalDeveloper:f8104adbecc0ec@localhost:27017/?authMechanism=DEFAULT
    database: db_todos
  devservices:
    enabled: false
  datasource:
    db-kind: oracle
#    reactive:
#      url: vertx-reactive:oracle:thin:@localhost:1521/devlocal
#      max-size: 10
    username: LocalDeveloper
    password: mxMVFk1TkRsaE1EUTJOelZ
    active: true
    default-data-source:
      name: oracle
    reactive:
      url: ["vertx-reactive:oracle:thin:@localhost:1521/devlocal"]
  #    mssql:
#      db-kind: mssql
#      reactive:
#        url: vertx-reactive:sqlserver://localhost:1433/master
#        max-size: 10
#      username: sa
#      password: YnBvQzJ2UVJxZw#
#      active: true
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
  log:
    console:
      enable: true
    level: DEBUG
  index-dependency:
    backend-dummy-project:
      group-id: 'com.my.dummy.project'
    java:
      group-id: 'com.my.dummy.project'
      artifact-id: 'backend-dummy-project'

rabbitmq:
  host: amqp
  port: 5672
  username: LocalRabbitMQMessagingQueue
  password: af3c4d5d01d790acc

mp:
  messaging:
    incoming:
      "todos.queue":
        connector: smallrye-rabbitmq
        durable: false
    outgoing:
      "todos.exchange":
        connector: smallrye-rabbitmq
        address: "todos.queue"

