---
# docker-compose -f docker-compose.yaml up -d
# https://hub.docker.com/_/microsoft-mssql-server
version: '3.8'
services:
  database:
    image: mcr.microsoft.com/mssql/server
    container_name: 'sqlserverdb2'
    hostname: 'localhost'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YnBvQzJ2UVJxZw#
    networks:
      - local_net_1
networks:
  local_net_1:
    driver: bridge
    external: true