---
version: "3.5"
services:
  rabbitmq:
    image: rabbitmq:3.13-rc-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=LocalRabbitMQMessagingQueue
      - RABBITMQ_DEFAULT_PASS=af3c4d5d01d790acc